---
- hosts: webservers
  become: yes
  tasks:
    - name: Instalar Apache
      yum:
        name: httpd
        state: present

    - name: Iniciar y habilitar Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

